select * from {{ ref('fct_order_line_fulfillment') }}
where FULFILLED_QUANTITY > ORDERED_QUANTITY or RETURNED_QUANTITY > FULFILLED_QUANTITY
   or FULFILLED_QUANTITY < 0 or RETURNED_QUANTITY < 0 or REFUND_CENTS < 0
   or RETAINED_REVENUE_CENTS <> LINE_NET_CENTS - REFUND_CENTS
