name: energy_pilot
version: 0.1.0
config-version: 2
profile: energy_pilot
model-paths:
- models
test-paths:
- tests
clean-targets:
- target
models:
  energy_pilot:
    +materialized: view
    +persist_docs:
      relation: false
      columns: false
